### ISSUE TITLE
To-do for local database integration

### ISSUE THREAD

**Issue by SelbiEreshova** [iVis-at-Bilkent/chise.js-sample-app#691]
[Branch](https://github.com/iVis-at-Bilkent/newt/tree/neo4j_integrate) 

**To do:**

- [ ] Merge menu bar options Query and Local database. 
- [ ] Change Database properties to Properties...
- [ ] Change Push Active Tab Contents to Push Contents
- [ ] Add CommonStream algorithms in Cypher if they are straightforward to implement
- [ ] Add different highlights for nodes and edges received from query. Check Visuall for reference
- [ ] Add option to merge when running a query (default unchecked)
- [ ] Add color scheme in database properties (reuse related Map properties if possible; if not, just have a text list of a few color schemes, not all)
- [ ] Handle other properties of nodes (state variable, unit information, etc... ) when adding nodes to canvas from database
- [x] Add JS promise for layout and highlight to be added after nodes and edges are adding
- [ ] Disable local database features if no .env file is found
- [ ] Add instructions in README for integrating local database to Newt
- [x] Create array of target nodes in neighborhood query and pass it to addNodesAndEdges function accordingly. The target nodes will be highlighted accordingly after this.
- [ ] Change neighborhood cypher query so it will not count process nodes when counting length

**Comment by ugurdogrusoz** [comment]
obsolete (see Noor's branch for this support)
